# -*- coding: utf-8 -*-
"""hate_speech_detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qsazqHOZP57VSwvXWVEd3K98jwMx60IH
"""

# Install all required libraries
!pip install transformers==4.35.0
!pip install torch
!pip install datasets
!pip install scikit-learn
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install sentencepiece
!pip install accelerate

# Check all libraries are working
import torch
import pandas as pd
import numpy as np
import sklearn
import transformers

print("✅ torch version:", torch.__version__)
print("✅ pandas version:", pd.__version__)
print("✅ numpy version:", np.__version__)
print("✅ sklearn version:", sklearn.__version__)
print("✅ transformers version:", transformers.__version__)
print("")
print("🎉 ALL LIBRARIES INSTALLED SUCCESSFULLY!")

# Fix the version conflict
!pip install transformers --upgrade
!pip install huggingface-hub --upgrade
!pip install accelerate --upgrade

# Reinstall with correct versions
!pip install transformers==4.40.0 huggingface-hub==0.23.0 -q

# Clean install - no version numbers
!pip install transformers huggingface-hub datasets accelerate -q --upgrade

# Restart runtime cleanly
import os
os.kill(os.getpid(), 9)

!pip install transformers huggingface-hub datasets accelerate -q --upgrade

import torch
import pandas as pd
import numpy as np
import sklearn
import transformers

print("✅ torch:", torch.__version__)
print("✅ pandas:", pd.__version__)
print("✅ numpy:", np.__version__)
print("✅ sklearn:", sklearn.__version__)
print("✅ transformers:", transformers.__version__)
print("")
print("🎉 ALL LIBRARIES WORKING!")

# This code will show a button to upload your files
from google.colab import files

print("📂 Click the 'Choose Files' button below to upload your datasets")
uploaded = files.upload()

import os

print("📂 All files in Colab:")
print("=" * 50)
for file in os.listdir('/content'):
    if file.endswith('.csv') or file.endswith('.xlsx'):
        size = os.path.getsize(f'/content/{file}')
        print(f"✅ {file}  →  {size/1024:.1f} KB")
print("=" * 50)

import pandas as pd

# Load Bengali (CSV)
df_bengali = pd.read_csv('/content/Bengali hate speech .csv')
print("✅ Bengali loaded:", df_bengali.shape)
print("   Columns:", df_bengali.columns.tolist())
print()

# Load Telugu training (XLSX)
df_telugu_train = pd.read_excel('/content/training_data_telugu-hate.xlsx')
print("✅ Telugu Train loaded:", df_telugu_train.shape)
print("   Columns:", df_telugu_train.columns.tolist())
print()

# Load Telugu test (XLSX)
df_telugu_test = pd.read_excel('/content/telugu-english-test-data-with-labels.xlsx')
print("✅ Telugu Test loaded:", df_telugu_test.shape)
print("   Columns:", df_telugu_test.columns.tolist())
print()

# Load train.csv
df_train = pd.read_csv('/content/train.csv')
print("✅ Train CSV loaded:", df_train.shape)
print("   Columns:", df_train.columns.tolist())
print()

print("🎉 ALL DATASETS LOADED!")

# Quick peek at all datasets
print("=" * 50)
print("📊 BENGALI - Label values:")
print(df_bengali['hate'].value_counts())

print("\n📊 TELUGU TRAIN - Label values:")
print(df_telugu_train['Label'].value_counts())

print("\n📊 TRAIN CSV - Class values:")
print(df_train['class'].value_counts())
print("=" * 50)

import pandas as pd
import numpy as np

print("=" * 50)
print("🔍 MISSING VALUES CHECK")
print("=" * 50)

print("\n📊 Bengali missing values:")
print(df_bengali.isnull().sum())

print("\n📊 Telugu Train missing values:")
print(df_telugu_train.isnull().sum())

print("\n📊 Train CSV missing values:")
print(df_train.isnull().sum())

print("\n✅ Missing values check done!")

print("=" * 50)
print("📊 DATASET SUMMARY")
print("=" * 50)

print("\n🔵 BENGALI DATASET:")
print(f"   Total rows    : {len(df_bengali)}")
print(f"   Hate rows     : {(df_bengali['hate']==1).sum()}")
print(f"   Not hate rows : {(df_bengali['hate']==0).sum()}")

print("\n🟢 TELUGU DATASET:")
print(f"   Total rows    : {len(df_telugu_train)}")
print(f"   Hate rows     : {(df_telugu_train['Label']=='hate').sum()}")
print(f"   Not hate rows : {(df_telugu_train['Label']=='non-hate').sum()}")

print("\n🟠 TRAIN CSV DATASET:")
print(f"   Total rows    : {len(df_train)}")
print(f"   Hate rows     : {(df_train['class']==0).sum()}")
print(f"   Offensive rows: {(df_train['class']==1).sum()}")
print(f"   Neither rows  : {(df_train['class']==2).sum()}")

print("\n✅ Summary done!")

import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['figure.figsize'] = (15, 5)

fig, axes = plt.subplots(1, 3, figsize=(15, 5))
fig.suptitle('📊 Label Distribution Across Datasets',
             fontsize=16, fontweight='bold')

# Bengali chart
bengali_counts = df_bengali['hate'].value_counts()
axes[0].bar(['Not Hate\n(0)', 'Hate\n(1)'],
            bengali_counts.values,
            color=['#2ecc71', '#e74c3c'],
            edgecolor='black')
axes[0].set_title('Bengali Dataset', fontweight='bold')
axes[0].set_ylabel('Number of rows')
for i, v in enumerate(bengali_counts.values):
    axes[0].text(i, v + 100, str(v), ha='center', fontweight='bold')

# Telugu chart
telugu_counts = df_telugu_train['Label'].value_counts()
axes[1].bar(['Non-Hate', 'Hate'],
            telugu_counts.values,
            color=['#2ecc71', '#e74c3c'],
            edgecolor='black')
axes[1].set_title('Telugu Dataset', fontweight='bold')
for i, v in enumerate(telugu_counts.values):
    axes[1].text(i, v + 10, str(v), ha='center', fontweight='bold')

# Train CSV chart
train_counts = df_train['class'].value_counts()
axes[2].bar(['Offensive\n(1)', 'Neither\n(2)', 'Hate\n(0)'],
            train_counts.values,
            color=['#f39c12', '#3498db', '#e74c3c'],
            edgecolor='black')
axes[2].set_title('Train CSV Dataset', fontweight='bold')
for i, v in enumerate(train_counts.values):
    axes[2].text(i, v + 50, str(v), ha='center', fontweight='bold')

plt.tight_layout()
plt.savefig('label_distribution.png', dpi=100, bbox_inches='tight')
plt.show()
print("✅ Charts saved!")

# Check average text length in each dataset
print("=" * 50)
print("📏 AVERAGE TEXT LENGTH")
print("=" * 50)

# Bengali
df_bengali['text_length'] = df_bengali['sentence'].astype(str).apply(len)
print(f"\n🔵 Bengali avg text length : {df_bengali['text_length'].mean():.0f} characters")
print(f"   Min length : {df_bengali['text_length'].min()}")
print(f"   Max length : {df_bengali['text_length'].max()}")

# Telugu
df_telugu_train['text_length'] = df_telugu_train['Comments'].astype(str).apply(len)
print(f"\n🟢 Telugu avg text length  : {df_telugu_train['text_length'].mean():.0f} characters")
print(f"   Min length : {df_telugu_train['text_length'].min()}")
print(f"   Max length : {df_telugu_train['text_length'].max()}")

# Train CSV
df_train['text_length'] = df_train['tweet'].astype(str).apply(len)
print(f"\n🟠 Train CSV avg text length: {df_train['text_length'].mean():.0f} characters")
print(f"   Min length : {df_train['text_length'].min()}")
print(f"   Max length : {df_train['text_length'].max()}")

print("\n✅ Text length check done!")

print("🔄 Combining all datasets into one...")

# Standardize Bengali
df_b = pd.DataFrame({
    'text'     : df_bengali['sentence'],
    'label'    : df_bengali['hate'],        # 0=not hate, 1=hate
    'language' : 'bengali'
})

# Standardize Telugu
df_t = pd.DataFrame({
    'text'     : df_telugu_train['Comments'],
    'label'    : df_telugu_train['Label'].map({'hate': 1, 'non-hate': 0}),
    'language' : 'telugu'
})

# Standardize Train CSV
# class 0=hate, 1=offensive, 2=neither
# We map: 0→1(hate), 1→1(hate/offensive), 2→0(not hate)
df_tr = pd.DataFrame({
    'text'     : df_train['tweet'],
    'label'    : df_train['class'].map({0: 1, 1: 1, 2: 0}),
    'language' : 'hindi_english'
})

# Combine all
df_combined = pd.concat([df_b, df_t, df_tr], ignore_index=True)

print(f"✅ Total combined rows : {len(df_combined)}")
print(f"✅ Hate rows           : {(df_combined['label']==1).sum()}")
print(f"✅ Not hate rows       : {(df_combined['label']==0).sum()}")
print(f"\n✅ Languages included:")
print(df_combined['language'].value_counts())
print("\n🎉 ALL DATASETS COMBINED!")

# Install text cleaning libraries
!pip install regex -q
!pip install emoji -q

print("✅ Cleaning libraries installed!")

import re
import emoji

def clean_text(text):
    # Step 1 - Convert to string (in case of numbers)
    text = str(text)

    # Step 2 - Remove URLs (http, www links)
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)

    # Step 3 - Remove @mentions (like @username)
    text = re.sub(r'@\w+', '', text)

    # Step 4 - Remove hashtags symbol but keep word (#hate → hate)
    text = re.sub(r'#', '', text)

    # Step 5 - Remove emojis
    text = emoji.replace_emoji(text, replace='')

    # Step 6 - Remove special characters but keep
    # Indian language characters + English letters
    text = re.sub(r'[^\w\s\u0900-\u097F\u0980-\u09FF\u0C00-\u0C7F\u0C80-\u0CFF]', ' ', text)

    # Step 7 - Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    # Step 8 - Remove very short texts (less than 3 characters)
    if len(text) < 3:
        return None

    return text

print("✅ Cleaning function created!")
print("🧹 Ready to clean text!")

print("🧹 Cleaning all text data...")
print("This may take 1-2 minutes...")
print()

# Clean the combined dataset
df_combined['text_clean'] = df_combined['text'].apply(clean_text)

# Count before and after
total_before = len(df_combined)
df_combined = df_combined.dropna(subset=['text_clean'])
total_after = len(df_combined)

print(f"✅ Rows before cleaning : {total_before}")
print(f"✅ Rows after cleaning  : {total_after}")
print(f"🗑️  Rows removed        : {total_before - total_after}")
print()
print("✅ Text cleaning done!")

# Show cleaning results (no raw text shown - just lengths)
print("=" * 50)
print("📏 CLEANING RESULTS")
print("=" * 50)

df_combined['original_length'] = df_combined['text'].astype(str).apply(len)
df_combined['cleaned_length']  = df_combined['text_clean'].astype(str).apply(len)

print(f"\n📊 Average original text length : {df_combined['original_length'].mean():.0f} chars")
print(f"📊 Average cleaned text length  : {df_combined['cleaned_length'].mean():.0f} chars")
print(f"\n✅ Label distribution after cleaning:")
print(df_combined['label'].value_counts())
print(f"\n✅ Language distribution after cleaning:")
print(df_combined['language'].value_counts())
print("=" * 50)

print("🏷️  Adding toxicity severity labels...")

def get_severity(row):
    # Not hate at all
    if row['label'] == 0:
        return 0  # clean

    # For hate speech - check length and source
    text_len = len(str(row['text_clean']))

    # Short hate text = mild
    if text_len < 50:
        return 1  # mild

    # Medium hate text = moderate
    elif text_len < 150:
        return 2  # moderate

    # Long hate text = severe
    else:
        return 3  # severe

df_combined['severity'] = df_combined.apply(get_severity, axis=1)

print("\n✅ Severity label distribution:")
severity_map = {0: 'Clean', 1: 'Mild', 2: 'Moderate', 3: 'Severe'}
for k, v in df_combined['severity'].value_counts().sort_index().items():
    print(f"   {severity_map[k]:10} ({k}) → {v:,} rows")

print("\n✅ Severity labels added!")

from sklearn.utils import resample

print("⚖️  Balancing the dataset...")

# Separate each class
df_clean    = df_combined[df_combined['label'] == 0]
df_hate     = df_combined[df_combined['label'] == 1]

print(f"\nBefore balancing:")
print(f"   Not hate : {len(df_clean):,}")
print(f"   Hate     : {len(df_hate):,}")

# Find the smaller class size
min_size = min(len(df_clean), len(df_hate))

# Downsample both to same size
df_clean_balanced = resample(df_clean,
                              n_samples=min_size,
                              random_state=42)
df_hate_balanced  = resample(df_hate,
                              n_samples=min_size,
                              random_state=42)

# Combine back
df_balanced = pd.concat([df_clean_balanced, df_hate_balanced])
df_balanced = df_balanced.sample(frac=1, random_state=42).reset_index(drop=True)

print(f"\nAfter balancing:")
print(f"   Not hate : {(df_balanced['label']==0).sum():,}")
print(f"   Hate     : {(df_balanced['label']==1).sum():,}")
print(f"   Total    : {len(df_balanced):,}")
print("\n✅ Dataset balanced!")

from sklearn.model_selection import train_test_split

print("✂️  Splitting data into Train and Test sets...")

# Use cleaned text and label columns
X = df_balanced['text_clean'].values
y = df_balanced['label'].values

# 80% training, 20% testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y        # keeps same ratio in both splits
)

print(f"\n✅ Training set   : {len(X_train):,} rows")
print(f"✅ Testing set    : {len(X_test):,} rows")
print(f"\n✅ Train label split:")
print(f"   Hate     : {y_train.sum():,}")
print(f"   Not hate : {(y_train==0).sum():,}")
print(f"\n✅ Test label split:")
print(f"   Hate     : {y_test.sum():,}")
print(f"   Not hate : {(y_test==0).sum():,}")
print("\n🎉 DATA IS READY FOR TRAINING!")

# Save the cleaned dataset so we don't lose it
df_balanced.to_csv('/content/cleaned_dataset.csv', index=False)

print("✅ Cleaned dataset saved as 'cleaned_dataset.csv'")
print(f"✅ Total rows saved : {len(df_balanced):,}")
print("\n🎉 STEP 4 COMPLETE!")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# Load the cleaned dataset we saved in Step 4
df = pd.read_csv('/content/cleaned_dataset.csv')

print(f"✅ Loaded cleaned dataset: {df.shape}")
print(f"✅ Hate rows    : {(df['label']==1).sum():,}")
print(f"✅ Not hate rows: {(df['label']==0).sum():,}")

# Split into train and test
X = df['text_clean'].fillna('').values
y = df['label'].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(f"\n✅ Training rows : {len(X_train):,}")
print(f"✅ Testing rows  : {len(X_test):,}")
print("\n✅ Data ready!")

from transformers import AutoTokenizer

print("⏳ Loading MuRIL tokenizer...")
print("This may take 2-3 minutes first time...")
print()

# MuRIL = Multilingual Representations for Indian Languages
# Made by Google specifically for Indian languages!
MODEL_NAME = "google/muril-base-cased"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

print("✅ MuRIL tokenizer loaded!")
print(f"✅ Vocabulary size: {tokenizer.vocab_size:,} words")
print("\n💡 MuRIL knows these languages:")
print("   Hindi, Bengali, Telugu, Tamil, Malayalam,")
print("   Kannada, Gujarati, Marathi, Punjabi + more!")

import torch
from torch.utils.data import Dataset, DataLoader

print("🔄 Tokenizing training data...")
print("Converting text → numbers the model understands...")
print()

# Max length of text (128 tokens is good for social media)
MAX_LEN = 128

# Tokenize training data
train_encodings = tokenizer(
    list(X_train),
    truncation=True,
    padding=True,
    max_length=MAX_LEN,
    return_tensors='pt'
)

# Tokenize test data
test_encodings = tokenizer(
    list(X_test),
    truncation=True,
    padding=True,
    max_length=MAX_LEN,
    return_tensors='pt'
)

print(f"✅ Training data tokenized!")
print(f"   Shape: {train_encodings['input_ids'].shape}")
print(f"\n✅ Testing data tokenized!")
print(f"   Shape: {test_encodings['input_ids'].shape}")
print("\n✅ Tokenization done!")

# Create a PyTorch Dataset
# This is how PyTorch reads our data during training

class HateSpeechDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels    = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {
            key: val[idx].clone().detach()
            for key, val in self.encodings.items()
        }
        item['labels'] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

# Create train and test datasets
train_dataset = HateSpeechDataset(train_encodings, y_train)
test_dataset  = HateSpeechDataset(test_encodings,  y_test)

print("✅ Train dataset created:", len(train_dataset), "samples")
print("✅ Test dataset created :", len(test_dataset),  "samples")
print("\n✅ Datasets ready for training!")

from transformers import AutoModelForSequenceClassification

print("⏳ Loading MuRIL model...")
print("This will take 3-5 minutes...")
print()

# Load MuRIL with 2 output labels (hate / not hate)
model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=2
)

# Move model to GPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = model.to(device)

print(f"✅ MuRIL model loaded!")
print(f"✅ Running on: {device}")
print(f"✅ Model parameters: {sum(p.numel() for p in model.parameters()):,}")
print("\n🤖 Model is ready for training!")

from torch.optim import AdamW
from transformers import get_linear_schedule_with_warmup

# Training settings
EPOCHS     = 3       # Number of times to go through all data
BATCH_SIZE = 16      # How many samples per step
LR         = 2e-5    # Learning rate (how fast model learns)

# Create data loaders
train_loader = DataLoader(train_dataset,
                          batch_size=BATCH_SIZE,
                          shuffle=True)
test_loader  = DataLoader(test_dataset,
                          batch_size=BATCH_SIZE,
                          shuffle=False)

# Optimizer - controls how model learns
optimizer = AdamW(model.parameters(), lr=LR)

# Scheduler - adjusts learning rate during training
total_steps = len(train_loader) * EPOCHS
scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=total_steps // 10,
    num_training_steps=total_steps
)

print("✅ Training settings configured!")
print(f"   Epochs        : {EPOCHS}")
print(f"   Batch size    : {BATCH_SIZE}")
print(f"   Learning rate : {LR}")
print(f"   Total steps   : {total_steps:,}")
print(f"   Train batches : {len(train_loader):,}")
print("\n✅ Ready to train!")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# Load cleaned dataset
df = pd.read_csv('/content/cleaned_dataset.csv')

# Take 30,000 rows only
df_small = df.sample(n=30000, random_state=42)

X = df_small['text_clean'].fillna('').values
y = df_small['label'].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(f"✅ Total rows     : 30,000")
print(f"✅ Training rows  : {len(X_train):,}")
print(f"✅ Testing rows   : {len(X_test):,}")
print(f"✅ Hate rows      : {y_train.sum():,}")
print(f"✅ Not hate rows  : {(y_train==0).sum():,}")
print("\n✅ 30K dataset ready!")

from transformers import AutoTokenizer

print("⏳ Loading MuRIL tokenizer...")
print("This may take 2-3 minutes first time...")

MODEL_NAME = "google/muril-base-cased"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

print("✅ MuRIL tokenizer loaded!")
print(f"✅ Vocabulary size: {tokenizer.vocab_size:,} words")

import torch
from torch.utils.data import Dataset, DataLoader

print("🔄 Tokenizing data...")
print("Converting text → numbers...")

MAX_LEN = 128

# Tokenize training data
train_encodings = tokenizer(
    list(X_train),
    truncation=True,
    padding=True,
    max_length=MAX_LEN,
    return_tensors='pt'
)

# Tokenize test data
test_encodings = tokenizer(
    list(X_test),
    truncation=True,
    padding=True,
    max_length=MAX_LEN,
    return_tensors='pt'
)

print(f"✅ Training data tokenized!")
print(f"   Shape: {train_encodings['input_ids'].shape}")
print(f"✅ Testing data tokenized!")
print(f"   Shape: {test_encodings['input_ids'].shape}")
print("\n✅ Tokenization done!")

from torch.utils.data import Dataset, DataLoader
import torch

class HateSpeechDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels    = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {
            key: val[idx].clone().detach()
            for key, val in self.encodings.items()
        }
        item['labels'] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

# Create datasets
train_dataset = HateSpeechDataset(train_encodings, y_train)
test_dataset  = HateSpeechDataset(test_encodings,  y_test)

print("✅ Train dataset:", len(train_dataset), "samples")
print("✅ Test dataset :", len(test_dataset),  "samples")
print("\n✅ Datasets ready!")

from transformers import AutoModelForSequenceClassification
import torch

print("⏳ Loading MuRIL model...")
print("This will take 3-5 minutes...")
print()

MODEL_NAME = "google/muril-base-cased"

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=2
)

# Move model to GPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model  = model.to(device)

print(f"✅ MuRIL model loaded!")
print(f"✅ Running on    : {device}")
print(f"✅ Total params  : {sum(p.numel() for p in model.parameters()):,}")
print("\n🤖 Model ready for training!")

from torch.optim import AdamW
from transformers import get_linear_schedule_with_warmup
from torch.utils.data import DataLoader

# Training settings
EPOCHS     = 3
BATCH_SIZE = 16
LR         = 2e-5

# Create data loaders
train_loader = DataLoader(train_dataset,
                          batch_size=BATCH_SIZE,
                          shuffle=True)
test_loader  = DataLoader(test_dataset,
                          batch_size=BATCH_SIZE,
                          shuffle=False)

# Optimizer
optimizer = AdamW(model.parameters(), lr=LR)

# Scheduler
total_steps = len(train_loader) * EPOCHS
scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=total_steps // 10,
    num_training_steps=total_steps
)

print("✅ Training settings configured!")
print(f"   Epochs        : {EPOCHS}")
print(f"   Batch size    : {BATCH_SIZE}")
print(f"   Learning rate : {LR}")
print(f"   Total steps   : {total_steps:,}")
print(f"   Train batches : {len(train_loader):,}")
print("\n✅ Ready to train!")

import time

print("🚀 STARTING TRAINING!")
print("=" * 50)
print("⏳ Expected time : ~35-45 minutes")
print("⚠️  Do NOT close this tab!")
print("=" * 50)

training_results = []

for epoch in range(EPOCHS):
    # ---- TRAINING PHASE ----
    model.train()
    total_train_loss = 0
    correct_train    = 0
    total_train      = 0
    start_time       = time.time()

    for batch_num, batch in enumerate(train_loader):
        input_ids      = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels         = batch['labels'].to(device)

        optimizer.zero_grad()

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels
        )

        loss   = outputs.loss
        logits = outputs.logits

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()

        total_train_loss += loss.item()
        predictions       = torch.argmax(logits, dim=1)
        correct_train    += (predictions == labels).sum().item()
        total_train      += labels.size(0)

        # Print progress every 100 batches
        if (batch_num + 1) % 100 == 0:
            avg_loss = total_train_loss / (batch_num + 1)
            acc      = correct_train / total_train * 100
            elapsed  = (time.time() - start_time) / 60
            print(f"  Epoch {epoch+1} | Batch {batch_num+1}/{len(train_loader)} "
                  f"| Loss: {avg_loss:.4f} | Acc: {acc:.1f}% | {elapsed:.1f} mins")

    # ---- VALIDATION PHASE ----
    model.eval()
    total_val_loss = 0
    correct_val    = 0
    total_val      = 0

    with torch.no_grad():
        for batch in test_loader:
            input_ids      = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels         = batch['labels'].to(device)

            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels
            )

            total_val_loss += outputs.loss.item()
            predictions     = torch.argmax(outputs.logits, dim=1)
            correct_val    += (predictions == labels).sum().item()
            total_val      += labels.size(0)

    # Epoch results
    train_acc  = correct_train / total_train * 100
    val_acc    = correct_val   / total_val   * 100
    train_loss = total_train_loss / len(train_loader)
    val_loss   = total_val_loss   / len(test_loader)
    elapsed    = (time.time() - start_time) / 60

    training_results.append({
        'epoch'     : epoch + 1,
        'train_acc' : train_acc,
        'val_acc'   : val_acc,
        'train_loss': train_loss,
        'val_loss'  : val_loss
    })

    print(f"\n{'='*50}")
    print(f"✅ EPOCH {epoch+1} DONE! ({elapsed:.1f} mins)")
    print(f"   Train Loss : {train_loss:.4f}")
    print(f"   Train Acc  : {train_acc:.2f}%")
    print(f"   Val Loss   : {val_loss:.4f}")
    print(f"   Val Acc    : {val_acc:.2f}%")
    print(f"{'='*50}\n")

print("🎉 TRAINING COMPLETE!")

import torch
import numpy as np

print("🔄 Getting predictions on test data...")
print("Please wait...")

model.eval()

all_predictions = []
all_true_labels = []

with torch.no_grad():
    for batch in test_loader:
        input_ids      = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels         = batch['labels'].to(device)

        outputs     = model(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

        predictions = torch.argmax(outputs.logits, dim=1)

        all_predictions.extend(predictions.cpu().numpy())
        all_true_labels.extend(labels.cpu().numpy())

all_predictions = np.array(all_predictions)
all_true_labels = np.array(all_true_labels)

print(f"✅ Total predictions made : {len(all_predictions):,}")
print(f"✅ Correct predictions    : {(all_predictions == all_true_labels).sum():,}")
print(f"✅ Wrong predictions      : {(all_predictions != all_true_labels).sum():,}")
print(f"\n✅ Overall Accuracy: {(all_predictions == all_true_labels).mean()*100:.2f}%")

from sklearn.metrics import classification_report

print("=" * 55)
print("📊 DETAILED CLASSIFICATION REPORT")
print("=" * 55)

report = classification_report(
    all_true_labels,
    all_predictions,
    target_names=['Not Hate (0)', 'Hate Speech (1)'],
    digits=4
)
print(report)
print("=" * 55)

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# Calculate confusion matrix
cm = confusion_matrix(all_true_labels, all_predictions)

# Plot it
plt.figure(figsize=(8, 6))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=['Not Hate', 'Hate Speech'],
    yticklabels=['Not Hate', 'Hate Speech'],
    linewidths=2
)

plt.title('🔍 Confusion Matrix', fontsize=16, fontweight='bold', pad=15)
plt.ylabel('Actual Label',    fontsize=12, fontweight='bold')
plt.xlabel('Predicted Label', fontsize=12, fontweight='bold')

# Add labels inside boxes
for i in range(2):
    for j in range(2):
        if i == j:
            plt.text(j+0.5, i+0.7, '✅ Correct',
                    ha='center', fontsize=9, color='green')
        else:
            plt.text(j+0.5, i+0.7, '❌ Wrong',
                    ha='center', fontsize=9, color='red')

plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=100, bbox_inches='tight')
plt.show()
print("✅ Confusion matrix saved!")

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

accuracy  = accuracy_score(all_true_labels,  all_predictions)
f1        = f1_score(all_true_labels,        all_predictions)
precision = precision_score(all_true_labels, all_predictions)
recall    = recall_score(all_true_labels,    all_predictions)

print("=" * 50)
print("🏆 FINAL MODEL PERFORMANCE SUMMARY")
print("=" * 50)
print(f"\n  ✅ Accuracy  : {accuracy*100:.2f}%")
print(f"  ✅ F1 Score  : {f1*100:.2f}%")
print(f"  ✅ Precision : {precision*100:.2f}%")
print(f"  ✅ Recall    : {recall*100:.2f}%")
print("\n" + "=" * 50)
print("📖 What these mean:")
print("  Accuracy  = overall correct predictions")
print("  F1 Score  = balance of precision & recall")
print("  Precision = when it says hate, how often correct")
print("  Recall    = how many actual hate posts it found")
print("=" * 50)
print("\n🎉 EVALUATION COMPLETE!")

import os

# Create folder to save model
os.makedirs('/content/hate_speech_model', exist_ok=True)

# Save model and tokenizer
model.save_pretrained('/content/hate_speech_model')
tokenizer.save_pretrained('/content/hate_speech_model')

print("✅ Model saved!")
print("✅ Tokenizer saved!")
print(f"\n📁 Saved files:")
for f in os.listdir('/content/hate_speech_model'):
    size = os.path.getsize(f'/content/hate_speech_model/{f}')
    print(f"   {f}  →  {size/1024/1024:.1f} MB")
print("\n🎉 Model saved successfully!")

from sklearn.metrics import classification_report

print("=" * 55)
print("📊 DETAILED CLASSIFICATION REPORT")
print("=" * 55)

report = classification_report(
    all_true_labels,
    all_predictions,
    target_names=['Not Hate (0)', 'Hate Speech (1)'],
    digits=4
)
print(report)
print("=" * 55)

import os

os.makedirs('/content/hate_speech_model', exist_ok=True)

model.save_pretrained('/content/hate_speech_model')
tokenizer.save_pretrained('/content/hate_speech_model')

print("✅ Model saved!")
print("✅ Tokenizer saved!")
print(f"\n📁 Saved files:")
for f in os.listdir('/content/hate_speech_model'):
    size = os.path.getsize(f'/content/hate_speech_model/{f}')
    print(f"   {f}  →  {size/1024/1024:.1f} MB")
print("\n🎉 Model saved successfully!")

import torch

def predict_hate_speech(text):
    inputs = tokenizer(
        text,
        truncation=True,
        padding=True,
        max_length=128,
        return_tensors='pt'
    ).to(device)

    model.eval()
    with torch.no_grad():
        outputs = model(**inputs)
        probs   = torch.softmax(outputs.logits, dim=1)
        pred    = torch.argmax(probs, dim=1).item()
        conf    = probs[0][pred].item() * 100

    if pred == 0:
        return {
            'prediction' : 'NOT HATE SPEECH ✅',
            'severity'   : 'Clean',
            'confidence' : f'{conf:.1f}%'
        }
    else:
        if conf >= 95:
            severity = '🔴 SEVERE'
        elif conf >= 80:
            severity = '🟠 MODERATE'
        else:
            severity = '🟡 MILD'
        return {
            'prediction' : 'HATE SPEECH ❌',
            'severity'   : severity,
            'confidence' : f'{conf:.1f}%'
        }

# Test with sample texts
test_texts = [
    "I love India and all its people",
    "আমি তোমাকে ভালোবাসি",
    "నేను మీతో సంతోషంగా ఉన్నాను",
]

print("🧪 TESTING MODEL")
print("=" * 50)
for text in test_texts:
    result = predict_hate_speech(text)
    print(f"\n📝 Text       : {text}")
    print(f"   Prediction : {result['prediction']}")
    print(f"   Severity   : {result['severity']}")
    print(f"   Confidence : {result['confidence']}")
print("=" * 50)
print("\n✅ Model testing done!")

!pip install gradio -q

print("✅ Gradio installed!")

import gradio as gr

def analyze_text(text):
    if not text or len(text.strip()) < 3:
        return "⚠️ Please enter some text!", "N/A", "N/A"

    result = predict_hate_speech(text)

    prediction = result['prediction']
    severity   = result['severity']
    confidence = result['confidence']

    if 'NOT HATE' in prediction:
        output = f"""
✅ SAFE CONTENT

Prediction  : {prediction}
Severity    : {severity}
Confidence  : {confidence}

This text does not contain hate speech.
        """
    else:
        output = f"""
❌ HATE SPEECH DETECTED

Prediction  : {prediction}
Severity    : {severity}
Confidence  : {confidence}

This text has been flagged for moderation.
        """

    return output, severity, confidence

# Build the interface
with gr.Blocks(title="🛡️ Hate Speech Detector",
               theme=gr.themes.Soft()) as dashboard:

    gr.Markdown("""
    # 🛡️ Multilingual Hate Speech Detector
    ### Detects hate speech in Hindi, Bengali, Telugu & more!
    ---
    """)

    with gr.Row():
        with gr.Column():
            text_input = gr.Textbox(
                label="📝 Enter Text To Analyze",
                placeholder="Type text here in any Indian language...",
                lines=5
            )
            analyze_btn = gr.Button(
                "🔍 Analyze Text",
                variant="primary",
                size="lg"
            )

        with gr.Column():
            output_box = gr.Textbox(
                label="📊 Analysis Result",
                lines=8,
                interactive=False
            )

    with gr.Row():
        severity_box   = gr.Textbox(
            label="⚠️ Severity Level",
            interactive=False
        )
        confidence_box = gr.Textbox(
            label="🎯 Confidence Score",
            interactive=False
        )

    analyze_btn.click(
        fn=analyze_text,
        inputs=text_input,
        outputs=[output_box, severity_box, confidence_box]
    )

    gr.Markdown("""
    ---
    ### 📖 Severity Levels
    - ✅ **Clean** — No hate speech detected
    - 🟡 **MILD** — Low confidence hate detection
    - 🟠 **MODERATE** — Medium confidence hate detection
    - 🔴 **SEVERE** — High confidence hate detection

    ### 🌐 Supported Languages
    Hindi • Bengali • Telugu • Tamil • Malayalam • English
    """)

print("🚀 Launching dashboard...")
dashboard.launch(share=True, debug=False)

Running on public URL: https://xxxxxx.gradio.live

